version: '2'
services:
  emby:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
    ports:
      - 8096:8096
      - 8920:8920
    volumes:
      - emby-data:/var/lib/emby
volumes:
  emby-data:
networks:
  internal:
    driver: bridge
